- name: Pull and run docker image
  hosts: host_machine
  tasks:
    - name: removing old containers
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm

    - name: pull image
      shell: docker pull avantikaaa/spe-mini-project:latest
      
    - name: run container
      shell: docker run -i --name calculator -d avantikaaa/spe-mini-project